### ISSUE TITLE
add_product_susedata fails to work with latest package translations update

### ISSUE THREAD

**Issue by nilxam** [openSUSE/instsource-susedata#1]
With latest package translations update https://build.opensuse.org/request/show/597099 , product-builder get the error while executing add_product_susedata, I pasted the last few lines of log here.

`[  906s] Apr-24 05:29:24 <1> : [I] ProductData:getVar(RPUse of uninitialized value in concatenation (.) or string at /usr/share/kiwi/modules/plugins/suse-tumbleweed/KIWIDescrPlugin.pm line 120.
[  906s] Use of uninitialized value $metadataonly in string eq at /usr/share/kiwi/modules/plugins/suse-tumbleweed/KIWIDescrPlugin.pm line 120.
[  906s] MHDRS_ONLY) is not set
[  906s] Apr-24 05:29:24 <1> : [I] Executing command <createrepo_c --unique-md-filenames --checksum=sha256 --no-database /usr/src/packages/KIWIROOT/main/Test-Build967.1-Media>
[  917s] Apr-24 05:29:35 <1> : [I] Executing command <rezip_repo_rsyncable /usr/src/packages/KIWIROOT/main/Test-Build967.1-Media >
[  922s] Apr-24 05:29:41 <1> : [I] Called /usr/bin/openSUSE-appstream-process /usr/src/packages/KIWIROOT/main/Test-Build967.1-Media /usr/src/packages/KIWIROOT/main/Test-Build967.1-Media/repodata exit status: <0> output: GLib-GIO-Message: 05:29:39.823: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
[  922s] Apr-24 05:29:41 <1> : [I] Executing command </usr/bin/add_product_susedata -u -k /usr/src/packages/SOURCES/PRODUCT-x86_64.kwd -p -e /usr/share/doc/packages/eulas -d /usr/src/packages/KIWIROOT/main/Test-Build967.1-Media>
[  923s] Apr-24 05:29:41 <3> : [E] Called </usr/bin/add_product_susedata -u -k /usr/src/packages/SOURCES/PRODUCT-x86_64.kwd -p -e /usr/share/doc/packages/eulas -d /usr/src/packages/KIWIROOT/main/Test-Build967.1-Media> exit status: <2> output: 
[  923s] 
`

inst-source-utils version is 20180406, haven't any further update there. I'm not sure it is because of bad character in package-translations or empty content, or something else. Any advise is welcome.

**Comment by adrianschroeter** [comment]
On Dienstag, 24. April 2018, 07:57:05 CEST wrote Max Lin:
> With latest package translations update https://build.opensuse.org/request/show/597099 , product-builder get the error while executing add_product_susedata, I pasted the last few lines of log here.
> 
> `[  906s] Apr-24 05:29:24 <1> : [I] ProductData:getVar(RPUse of uninitialized value in concatenation (.) or string at /usr/share/kiwi/modules/plugins/suse-tumbleweed/KIWIDescrPlugin.pm line 120.
> [  906s] Use of uninitialized value $metadataonly in string eq at /usr/share/kiwi/modules/plugins/suse-tumbleweed/KIWIDescrPlugin.pm line 120.
> [  906s] MHDRS_ONLY) is not set
> [  906s] Apr-24 05:29:24 <1> : [I] Executing command <createrepo_c --unique-md-filenames --checksum=sha256 --no-database /usr/src/packages/KIWIROOT/main/Test-Build967.1-Media>
> [  917s] Apr-24 05:29:35 <1> : [I] Executing command <rezip_repo_rsyncable /usr/src/packages/KIWIROOT/main/Test-Build967.1-Media >
> [  922s] Apr-24 05:29:41 <1> : [I] Called /usr/bin/openSUSE-appstream-process /usr/src/packages/KIWIROOT/main/Test-Build967.1-Media /usr/src/packages/KIWIROOT/main/Test-Build967.1-Media/repodata exit status: <0> output: GLib-GIO-Message: 05:29:39.823: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
> [  922s] Apr-24 05:29:41 <1> : [I] Executing command </usr/bin/add_product_susedata -u -k /usr/src/packages/SOURCES/PRODUCT-x86_64.kwd -p -e /usr/share/doc/packages/eulas -d /usr/src/packages/KIWIROOT/main/Test-Build967.1-Media>
> [  923s] Apr-24 05:29:41 <3> : [E] Called </usr/bin/add_product_susedata -u -k /usr/src/packages/SOURCES/PRODUCT-x86_64.kwd -p -e /usr/share/doc/packages/eulas -d /usr/src/packages/KIWIROOT/main/Test-Build967.1-Media> exit status: <2> output: 
> [  923s] 
> `
> 
> inst-source-utils version is 20180406, haven't any further update there. I'm not sure it is because of bad character in package-translations or empty content, or something else. Any advise is welcome.

This seems to be new enough. Where do you see this failure exactly, because openSUSE:Factory had successful builds.

The version update of that package was forgotten in 15 code line where I submitted it yesterday to
fix exactly such an error.

In any case, an exact URL to the build would be helpful

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany

**Comment by nilxam** [comment]
I just unselected package-translations from staging project to backlog, just adding it back, fortunately the Test-DVD build should not be affected, thus https://build.opensuse.org/package/live_build_log/openSUSE:Factory:Staging:E/Test-DVD-x86_64/images/x86_64 is the build with this error.

**Comment by nilxam** [comment]
Or this issue has been fixed in https://build.opensuse.org/request/show/597728 ?

**Comment by nilxam** [comment]
> Or this issue has been fixed in https://build.opensuse.org/request/show/597728 ?

Update: No, DVD build failure still appears with instsource-susedata 0.3.2.

**Comment by adrianschroeter** [comment]
On Dienstag, 24. April 2018, 10:13:48 CEST wrote Max Lin:
> > Or this issue has been fixed in https://build.opensuse.org/request/show/597728 ?
> 
> Update: No, DVD build failure still appears with instsource-susedata 0.3.2.

Please give a URL for that

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany

**Comment by nilxam** [comment]
Same URL: https://build.opensuse.org/package/live_build_log/openSUSE:Factory:Staging:E/Test-DVD-x86_64/images/x86_64

**Comment by adrianschroeter** [comment]
On Dienstag, 24. April 2018, 09:14:02 CEST wrote Max Lin:
> Or this issue has been fixed in https://build.opensuse.org/request/show/597728 ?

no, missing dep to a perl module. New submission of version 0.3.3 is there.

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany

**Comment by nilxam** [comment]
Fixed.
